name: Deploy VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run Deploy Script
        shell: powershell
        run: |
          powershell -ExecutionPolicy Bypass -File "C:\www\vienbaovethuonghieu\deploy\deploy.ps1"
